-- Cria o banco de dados chamado 'biblioteca' se ele não existir
CREATE DATABASE IF NOT EXISTS biblioteca;

-- Seleciona o banco de dados 'biblioteca' para uso
USE biblioteca;

-- Cria a tabela chamada 'livros' se ela não existir
CREATE TABLE IF NOT EXISTS livros (
    id INT AUTO_INCREMENT PRIMARY KEY,
    titulo VARCHAR(255) NOT NULL,
    autor VARCHAR(255) NOT NULL,
    ano_publicacao INT
);

-- Insere 100 registros de títulos de livros conhecidos
INSERT INTO livros (titulo, autor, ano_publicacao) VALUES
('Dom Quixote', 'Miguel de Cervantes', 1605),
('Cem Anos de Solidão', 'Gabriel García Márquez', 1967),
('1984', 'George Orwell', 1949),
('O Pequeno Príncipe', 'Antoine de Saint-Exupéry', 1943),
('Orgulho e Preconceito', 'Jane Austen', 1813),
('A Metamorfose', 'Franz Kafka', 1915),
('O Senhor dos Anéis', 'J.R.R. Tolkien', 1954),
('Harry Potter e a Pedra Filosofal', 'J.K. Rowling', 1997),
('O Código Da Vinci', 'Dan Brown', 2003),
('O Alquimista', 'Paulo Coelho', 1988),
('Memórias Póstumas de Brás Cubas', 'Machado de Assis', 1881),
('Vidas Secas', 'Graciliano Ramos', 1938),
('A Hora da Estrela', 'Clarice Lispector', 1977),
('Grande Sertão: Veredas', 'João Guimarães Rosa', 1956),
('Dom Casmurro', 'Machado de Assis', 1899),
('O Cortiço', 'Aluísio Azevedo', 1890),
('Iracema', 'José de Alencar', 1865),
('Os Lusíadas', 'Luís Vaz de Camões', 1572),
('Ensaio sobre a Cegueira', 'José Saramago', 1995),
('O Evangelho Segundo Jesus Cristo', 'José Saramago', 1991),
('Admirável Mundo Novo', 'Aldous Huxley', 1932),
('Fahrenheit 451', 'Ray Bradbury', 1953),
('O Morro dos Ventos Uivantes', 'Emily Brontë', 1847),
('Moby Dick', 'Herman Melville', 1851),
('A Letra Escarlate', 'Nathaniel Hawthorne', 1850),
('Crime e Castigo', 'Fiódor Dostoiévski', 1866),
('Os Irmãos Karamázov', 'Fiódor Dostoiévski', 1880),
('Guerra e Paz', 'Liev Tolstói', 1869),
('Anna Karenina', 'Liev Tolstói', 1877),
('Madame Bovary', 'Gustave Flaubert', 1856),
('O Estrangeiro', 'Albert Camus', 1942),
('A Peste', 'Albert Camus', 1947),
('O Processo', 'Franz Kafka', 1925),
('O Castelo', 'Franz Kafka', 1926),
('Ulisses', 'James Joyce', 1922),
('O Grande Gatsby', 'F. Scott Fitzgerald', 1925),
('O Velho e o Mar', 'Ernest Hemingway', 1952),
('Para Onde Voam as Gaivotas', 'Mia Couto', 2000),
('Terra Sonâmbula', 'Mia Couto', 1992),
('A Varanda do Frangipani', 'Mia Couto', 1996),
('Nove Noites', 'Bernardo Carvalho', 2002),
('Estação Brasil', 'Fernando Morais', 1999),
('Olhos D’Água', 'Conceição Evaristo', 2014),
('Ponciá Vicêncio', 'Conceição Evaristo', 2003),
('Quarto de Despejo', 'Carolina Maria de Jesus', 1960),
('Casa-Grande & Senzala', 'Gilberto Freyre', 1933),
('Raízes do Brasil', 'Sérgio Buarque de Holanda', 1936),
('Os Sertões', 'Euclides da Cunha', 1902),
('Triste Fim de Policarpo Quaresma', 'Lima Barreto', 1915),
('O Ateneu', 'Raul Pompeia', 1888),
('Amar, Verbo Intransitivo', 'Mário de Andrade', 1927),
('Macunaíma', 'Mário de Andrade', 1928),
('São Bernardo', 'Graciliano Ramos', 1934),
('Angústia', 'Graciliano Ramos', 1936),
('Capitães da Areia', 'Jorge Amado', 1937),
('Gabriela, Cravo e Canela', 'Jorge Amado', 1958),
('Dona Flor e Seus Dois Maridos', 'Jorge Amado', 1966),
('Tieta do Agreste', 'Jorge Amado', 1977),
('O Quinze', 'Rachel de Queiroz', 1930),
('As Meninas', 'Lygia Fagundes Telles', 1973),
('Ciranda de Pedra', 'Lygia Fagundes Telles', 1954),
('Verão no Aquário', 'Lygia Fagundes Telles', 1963),
('Incidente em Antares', 'Érico Veríssimo', 1971),
('O Tempo e o Vento', 'Érico Veríssimo', 1949),
('Olhai os Lírios do Campo', 'Érico Veríssimo', 1938),
('O Continente', 'Érico Veríssimo', 1949),
('O Retrato de Dorian Gray', 'Oscar Wilde', 1890),
('Drácula', 'Bram Stoker', 1897),
('Frankenstein', 'Mary Shelley', 1818),
('O Médico e o Monstro', 'Robert Louis Stevenson', 1886),
('As Aventuras de Sherlock Holmes', 'Arthur Conan Doyle', 1892),
('O Cão dos Baskervilles', 'Arthur Conan Doyle', 1902),
('O Hobbit', 'J.R.R. Tolkien', 1937),
('O Silmarillion', 'J.R.R. Tolkien', 1977),
('As Crônicas de Nárnia', 'C.S. Lewis', 1950),
('O Nome da Rosa', 'Umberto Eco', 1980),
('O Pêndulo de Foucault', 'Umberto Eco', 1988),
('O Cemitério de Praga', 'Umberto Eco', 2010),
('O Conto da Aia', 'Margaret Atwood', 1985),
('O Testamento', 'Margaret Atwood', 2019),
('As Benevolentes', 'Jonathan Littell', 2006),
('A Elegância do Ouriço', 'Muriel Barbery', 2006),
('O Caçador de Pipas', 'Khaled Hosseini', 2003),
('A Cidade do Sol', 'Khaled Hosseini', 2007),
('E o Vento Levou...', 'Margaret Mitchell', 1936),
('O Sol Também se Levanta', 'Ernest Hemingway', 1926),
('Por Quem os Sinos Dobram', 'Ernest Hemingway', 1940),
('A Revolução dos Bichos', 'George Orwell', 1945),
('O Senhor das Moscas', 'William Golding', 1954),
('O Apanhador no Campo de Centeio', 'J.D. Salinger', 1951),
('Quem Mexeu no Meu Queijo?', 'Spencer Johnson', 1998),
('O Monge que Vendeu sua Ferrari', 'Robin Sharma', 1997),
('Pai Rico, Pai Pobre', 'Robert Kiyosaki', 1997),
('Os Sete Maridos de Evelyn Hugo', 'Taylor Jenkins Reid', 2017),
('Daisy Jones & The Six', 'Taylor Jenkins Reid', 2019),
('Pequenos Incêndios por Toda Parte', 'Celeste Ng', 2017),
('Tudo o Que Nunca Nos Disseram', 'Celeste Ng', 2014),
('A Amiga Genial', 'Elena Ferrante', 2011),
('O Nome Perdido da Amiga Genial', 'Elena Ferrante', 2012),
('Aqueles que Partem e Aqueles que Ficam', 'Elena Ferrante', 2013),
('A História da Menina Perdida', 'Elena Ferrante', 2014)
;

-- Para verificar os registros inseridos, você pode usar o seguinte comando:
-- SELECT COUNT(*) FROM livros;
-- SELECT * FROM livros LIMIT 10;